Create v1.0.1.md
harvester/release-notes pull request #15
Opened 2022-03-18 22:15 UTC by rebeccazzzz

Release note draft for v1.0.1

2022-03-18 22:15 UTC, yasker submitted a review, later dismissed

2022-03-26 09:00 UTC, guangbochen requested changes

2022-03-26 09:00 UTC, guangbochen commented on v1.0.1.md
> +* When using Load Balancer IPAM `Pool`s, user is only able to provision 1 LB successfully. Subsequent LBs using `Pool` will fail [[#2041](https://github.com/harvester/harvester/issues/2041)]
Can u please check with David or Lanfo if they can reproduce it? at least I can't reproduce it in my env so might be an env related issue.

2022-03-27 23:23 UTC, rebeccazzzz commented on v1.0.1.md
> +Harvester v1.0.1 is the second General Availability (GA) release of Harvester!
Changed line 3 to the suggested text.

2022-03-27 23:23 UTC, rebeccazzzz commented on v1.0.1.md
> +* Manual upgrade from 0.3.0 to 1.0.0 [[#1665](https://github.com/harvester/harvester/issues/1665)]
Removed “manual upgrade from 0.3.0 to 1.0.0” from known issues.

2022-03-27 23:24 UTC, rebeccazzzz commented on v1.0.1.md
> +
Added suggested contributors.

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +Thanks to all the contributors that make Harvester v1.0.1 GA possible!
```suggestion
Thanks to all the contributors that make the Harvester v1.0.1 release possible!
```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +
```suggestion
:white_check_mark: [version.yaml](https://releases.rancher.com/harvester/v1.0.1/version.yaml)

```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +@rosskirkpat
```suggestion
@rosskirkpat 
@slash2314
```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +* Upgrade from v1.0.0. [[#1861](https://github.com/harvester/harvester/issues/1861)]
```suggestion
* Upgrade from v1.0.0. [[#1861](https://github.com/harvester/harvester/issues/1861)] [[Doc](https://docs.harvesterhci.io/v1.0/upgrade/automatic/)]
```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +* IPAM deployment through rancher is not working -> `health checks` disabled by default [[#2077](https://github.com/harvester/harvester/issues/2077)]
```suggestion
* Deleting a host holding the VIP in the cluster makes the VIP inaccessible [[#1398](https://github.com/harvester/harvester/issues/1398)]

* When using Load Balancer IPAM `Pool`s, user is only able to provision 1 LB successfully. Subsequent LBs using `Pool` will fail [[#2041](https://github.com/harvester/harvester/issues/2041)]
* Upgrade: longhorn-system can't be evicted [[#2053](https://github.com/harvester/harvester/issues/2053)]
* Predictable interface names deviate from previous versions [[#2073](https://github.com/harvester/harvester/issues/2073)]
* Upgrade related:
  * rancher-monitoring charts can't be upgraded [[#1983](https://github.com/harvester/harvester/issues/1983)]
  * Rancher upgrade fail: Failed to find system chart "fleet" [[#2011](https://github.com/harvester/harvester/issues/2011)]
  * VMs fail to live-migrate to other hosts in some cases [[#2029](https://github.com/harvester/harvester/issues/2029)]
```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +* [VM Scheduling](https://harvesterhci.io/kb/vm-scheduling)
```suggestion
* [VM Scheduling](https://harvesterhci.io/kb/vm-scheduling)
* [NIC Naming Scheme changed after upgrading to v1.0.1](https://harvesterhci.io/kb/nic-naming-scheme)
```

2022-04-08 06:38 UTC, guangbochen commented on v1.0.1.md
> +| RKE2 | [v1.22.7+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.22.7%2Brke2r1) |
```suggestion
| RKE2 | [v1.21.11+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.21.11%2Brke2r1) |
```

2022-04-08 13:10 UTC, guangbochen approved these changes

2022-04-08 13:10 UTC, merged